### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by akhtyamovpavel** [ftvkyo2011-study/pt-strategy#12]
Добрый день! Проверил ваше задание - очень интересный проект!

По паттернам замечаний нет - есть замечания по коду:

- [x] https://github.com/ftvkyo2011-study/pt-strategy/blob/master/src/main/java/Model/Unit/ArcherUnit.java#L16 - комментирование лучше убирать, git хранит историю изменений.
- [x] Не понял, зачем нужны файлы `ThickModel` и `ThinModel`, можете пояснить?
- [x] Что обозначают константы в `setPasableness`?

А в целом - все хорошо, задание принято

**Comment by AlekIks** [comment]
Здравствуйте! Мы хотели реализовать сеть, в ней Толстая модель  - сервер, а Тонкие - клиенты.
setPossableness - это количество очков действия, которые нужно потратить юниту, чтобы пройти по конкретной клетке.

**Comment by akhtyamovpavel** [comment]
Отлично!
