### ISSUE TITLE
Запуск графики под MacOS

### ISSUE THREAD

**Issue by akhtyamovpavel** [ftvkyo2011-study/pt-strategy#46]
**Описание бага**
...

**Как воспроизвести**
`./gradlew run`

**Ожидаемое поведение**
Запуск приложения

**Система:**
 - OS: MacOS
 - OS Version: [...]

**Дополнительная информация**
Выводит следующую ошибку: 
```
Caused by: java.lang.IllegalStateException: GLFW windows may only be created on the main thread and that thread must be the first thread in the process. Please run the JVM with -XstartOnFirstThread. For offscreen rendering, make sure another window toolkit (e.g. AWT or JavaFX) is initialized before GLFW.
```
<img width="1440" alt="screen shot 2018-05-23 at 09 35 47" src="https://user-images.githubusercontent.com/5366960/40407323-b5bb893c-5e6c-11e8-8826-ae5ce2aae344.png">

**Comment by ftvkyo2011** [comment]
У меня есть идея, что это пофиксит. И еще это может быть связано со старым OpenGL.

**Comment by ftvkyo2011** [comment]
@akhtyamovpavel 
Тут есть пулл-реквест #43 , там поновее чуток графика, например игра умеет выводить игровое поле. На данный момент розовая кнопка начинеат игру с повторной генерацией поля, зеленая "продолжает", красная выходит Игра->Настройки->Выход, серенькая - моя гордость)))), реализация Checkbox.
Вы можете
```bash
git checkout graphics
git pull
./gradlew run
```
Вроде бы я добавил туда штуку, которая позволит исправить вашу ошибку.
